CREATE TABLE FACULTY(
NUM INTEGER NOT NULL, PRIMARY KEY(NUM)
);


CREATE TABLE STUDENT(
ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
FAC_NUM INTEGER, FOREIGN KEY(FAC_NUM) REFERENCES FACULTY(NUM)
);

CREATE TABLE COURSE(
ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),
NAME VARCHAR(255) NOT NULL,
DESCRIPTION VARCHAR(255),
CREDITS INTEGER NOT NULL
);

CREATE TABLE COURSE_STUDENT(
ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),
COURSE_ID INTEGER NOT NULL, FOREIGN KEY(COURSE_ID) REFERENCES COURSE(ID),
STUDENT_ID INTEGER NOT NULL, FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID)
);