CREATE TABLE ADDRESS(
ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),
COUNTRY VARCHAR(255) NOT NULL,
CITY VARCHAR(255) NOT NULL,
STREET VARCHAR(255) NOT NULL,
NUMBER INTEGER NOT NULL
);

CREATE TABLE COMPANY(
ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),
NAME VARCHAR(255) NOT NULL,
ADDRESS_ID INTEGER, FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ID)

);

CREATE TABLE CUSTOMER(
ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
ADDRESS_ID INTEGER, FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ID)
);

CREATE TABLE PRODUCT(
ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),
NAME VARCHAR(255),
CATEGORY VARCHAR(255),
COMPANY_ID INTEGER, FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(ID),
PRICE DECIMAL(65, 2)
);

CREATE TABLE PURCHASE(
ID INTEGER NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID),
TIME DATETIME NOT NULL,
CUSTOMER_ID INTEGER NOT NULL, FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE PURCHASED_ITEMS(
PURCHASE_ID INTEGER, FOREIGN KEY(PURCHASE_ID) REFERENCES PURCHASE(ID),
PRODUCT_ID INTEGER NOT NULL, FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID),
QUANTITY INTEGER NOT NULL
);

INSERT INTO ADDRESS VALUES(NULL, 'Bulgaria','Sofia','Lale',15),
(NULL, 'Bulgaria', 'Sofia', 'Rila', 36),
(NULL, 'Bulgaria','Sofia','Stambolijski',14),
(NULL, 'Germany','Berlin','HelloStrasse',168),
(NULL, 'France','Paris','Chance Elysee',1);

INSERT INTO COMPANY VALUES(NULL, 'Sweets maker',1),
(NULL, 'BG Bakery', 2),
(NULL, 'FR Bakery',5);

INSERT INTO CUSTOMER VALUES(NULL, 'Matias','Muller', 4),(NULL, 'Ivan', 'Ivanov', 3);

INSERT INTO PRODUCT VALUES(NULL,'Kifla','Sweets', 1,1.12),
(NULL, 'Vafla','Sweets', 1, 0.62),
(NULL, 'Croissant','Sweets', 3, 1.99),
(NULL, 'Franzela','Bakery',3, 2.40);

INSERT INTO PURCHASE VALUES(NULL, '2018-09-06 10:53:14', 1),
(NULL, '2017-09-06 10:53:14', 2);

INSERT INTO PURCHASED_ITEMS VALUES(1,2,6),
(1,4,2),
(1,3,1),
(2,1,5);

SELECT FIRST_NAME, LAST_NAME FROM CUSTOMER WHERE ADDRESS_ID IN( SELECT ID FROM ADDRESS WHERE COUNTRY = 'Bulgaria');
 
SELECT p.NAME FROM PRODUCT AS p JOIN COMPANY AS c ON p.COMPANY_ID = c.ID;

SELECT p.NAME,c.NAME FROM PRODUCT AS p JOIN COMPANY AS c ON p.COMPANY_ID = c.ID;

SELECT p.NAME,c.NAME FROM PRODUCT AS p JOIN COMPANY AS c ON p.COMPANY_ID = c.ID WHERE c.NAME = 'FR Bakery';

SELECT PRODUCT.NAME, PURCHASED_ITEMS.QUANTITY FROM PRODUCT JOIN PURCHASED_ITEMS ON PRODUCT.ID = PURCHASED_ITEMS.PRODUCT_ID;

SELECT PRODUCT.NAME, PURCHASED_ITEMS.QUANTITY, PURCHASE.TIME FROM PRODUCT JOIN PURCHASED_ITEMS ON PRODUCT.ID = PURCHASED_ITEMS.PRODUCT_ID JOIN PURCHASE ON PURCHASE.ID = PURCHASED_ITEMS.PURCHASE_ID;
 

